<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Absent Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9799b9ed-27cf-42da-a728-fc3bf7fa0c61</testSuiteGuid>
   <testCaseLink>
      <guid>f57eea6e-f3e4-43dc-94d7-79aa9eecbfcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Clocking In/Clocking In Selfie</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f31da101-ecfb-4a27-9958-31d4ec487052</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/User/Clocking In Selfie</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f31da101-ecfb-4a27-9958-31d4ec487052</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>8ab6954f-239b-48c4-9795-728dd91e7ebd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f31da101-ecfb-4a27-9958-31d4ec487052</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>fbf83437-87e9-46f8-9169-94869fa5c37d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f31da101-ecfb-4a27-9958-31d4ec487052</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>note</value>
         <variableId>92b53556-ed41-4235-82be-6bfc1ee7cac3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4c44c1c-0e8e-4108-b9cc-59f8ebd1976f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Clocking In/Clocking In Non-Selfie</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5ff4ffd7-1846-4633-8fd0-8581438c6b74</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/User/Clocking In Nonselfie</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5ff4ffd7-1846-4633-8fd0-8581438c6b74</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>cad4b553-3063-4ec3-a618-3de2b8402ae4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5ff4ffd7-1846-4633-8fd0-8581438c6b74</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>92f1da66-a20d-41e3-b187-ca288cc9ad1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5ff4ffd7-1846-4633-8fd0-8581438c6b74</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>note</value>
         <variableId>fa799387-f4c0-44d2-a56b-f6791074506f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6efbbc3-0e3e-4c15-a311-271ce8a3db28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Clocking In/Clocking In Failed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b799ed9c-ef3b-472b-9bab-5c94c92b94c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/Clocking In/Clocking Out Successful</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>afbccf79-9cd9-4cc4-a094-f7b45ad8fd96</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/User/Clocking Out</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>afbccf79-9cd9-4cc4-a094-f7b45ad8fd96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>fe5a192a-d0d4-4a2e-8ff6-da1ab1c6e87a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>afbccf79-9cd9-4cc4-a094-f7b45ad8fd96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f0be6a52-2c05-448b-935b-8a68b0557b07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>afbccf79-9cd9-4cc4-a094-f7b45ad8fd96</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>note</value>
         <variableId>c068fdc4-a787-48d3-bbd2-22ed7952082e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
